@extends('emails.layouts.customMail')

@section('content')
    <div
        style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; color: #333; background-color: #f9f9f9; padding: 30px; border-radius: 8px; box-shadow: 0 2px 8px rgba(0,0,0,0.05);">

        <h2 style="color: #e74c3c;">Equipment Alert ⚠️</h2>

        <p style="font-size: 16px; line-height: 1.6;">
            Hello {{ $admin->name }},<br><br>
            This is to notify you that an equipment item has been marked as <strong style="color: #e74c3c;">non-functional</strong> and requires immediate attention.
        </p>

        <div style="background-color: #fdf2f2; padding: 20px; border-radius: 6px; margin: 20px 0; border-left: 4px solid #e74c3c;">
            <h3 style="color: #e74c3c; margin-top: 0;">Equipment Details:</h3>
            <p style="margin: 5px 0;"><strong>Reference:</strong> {{ $equipment->reference }}</p>
            <p style="margin: 5px 0;"><strong>Brand:</strong> {{ $equipment->mark }}</p>
            <p style="margin: 5px 0;"><strong>Type:</strong> {{ $equipment->equipmentType->name ?? 'Unknown' }}</p>
            <p style="margin: 5px 0;"><strong>Equipment ID:</strong> #{{ $equipment->id }}</p>
            <p style="margin: 5px 0;"><strong>Status:</strong> <span style="color: #e74c3c; font-weight: bold;">Non-Functional</span></p>
            <p style="margin: 5px 0;"><strong>Reported Date:</strong> {{ now()->format('Y-m-d H:i:s') }}</p>
        </div>

        <div style="background-color: #fff3cd; padding: 15px; border-radius: 6px; margin: 20px 0; border-left: 4px solid #ffc107;">
            <h4 style="color: #856404; margin-top: 0;">Required Actions:</h4>
            <ul style="color: #856404; margin: 10px 0;">
                <li>Inspect the equipment for damage or malfunction</li>
                <li>Schedule repair or replacement if necessary</li>
                <li>Update equipment status in the system</li>
                <li>Notify users if reservations are affected</li>
            </ul>
        </div>

        <p style="font-size: 16px; line-height: 1.6;">
            Please take immediate action to address this equipment issue. If you need to update the equipment status or have any questions, please access the admin panel.
        </p>

        <p style="font-size: 15px; color: #555;">
            This notification was automatically generated by the <strong>LionsGeek</strong> equipment management system.
        </p>

        <p style="margin-top: 40px; font-size: 15px;">
            Best regards,<br>
            The <strong>LionsGeek</strong> Equipment Management System 🦁
        </p>
    </div>
@endsection

